#!/usr/bin/env bash
set -euo pipefail

# Download OpenCC dictionary files and generate individual TypeScript modules.

# Pin to a specific commit for reproducible builds.
# As of August 23, 2026 the latest release is https://github.com/BYVoid/OpenCC/releases/tag/ver.1.4.2
COMMIT="025f371dc76b598d77384fbdab90c937471844d8"
REPO="https://raw.githubusercontent.com/BYVoid/OpenCC/${COMMIT}/data/dictionary"
DICT_DIR="src/dict"

DICT_FILES=(
  STCharacters STPhrases
  TSCharacters TSPhrases
  TWPhrases TWPhrasesRev
  TWVariants TWVariantsRevPhrases
)

# Reverse maps: "Source:Target" — swap key↔value from Source, save as Target.
#
# OpenCC provides most reverse maps we need, but not all:
#
#   File                  | From OpenCC? | Notes
#   ----------------------|--------------|-------------------------------
#   STCharacters          | yes          |
#   STPhrases             | yes          |
#   TSCharacters          | yes          |
#   TSPhrases             | yes          |
#   TWPhrases             | yes          |
#   TWPhrasesRev          | yes          |
#   TWVariants            | yes          |
#   TWVariantsRevPhrases  | yes          |
#   TWVariantsRev         | NO           | Generated by reversing TWVariants
#
REVERSE_MAPS=(
  "TWVariants:TWVariantsRev"
)

# Dictionaries where identity entries (key === value) must be kept as phrase
# shields — they prevent character-level rules from splitting known phrases.
KEEP_IDENTITY=(
  TWVariantsRevPhrases
)

mkdir -p "$DICT_DIR"

echo "==> Downloading dictionaries (commit: ${COMMIT:0:7}) ..."
for name in "${DICT_FILES[@]}"; do
  if ! curl -sfL "$REPO/${name}.txt" -o "$DICT_DIR/${name}.txt"; then
    echo "ERROR: Failed to download ${name}.txt"
    exit 1
  fi
  echo "    $name.txt"
done

echo "==> Generating TypeScript modules ..."
node scripts/gen-dict.js "$DICT_DIR" "${DICT_FILES[*]}" "${REVERSE_MAPS[*]}" "${KEEP_IDENTITY[*]}"

rm -f "$DICT_DIR"/*.txt

echo "==> Verifying exclusions ..."
if grep -q '"核心"' "$DICT_DIR/TWPhrasesRev.ts"; then
  echo "ERROR: TWPhrasesRev.ts still contains excluded key \"核心\""
  exit 1
fi
echo "    OK"

echo "==> Done."
