#!/usr/bin/env node
"use strict";

// Generate TypeScript modules from downloaded OpenCC dictionary .txt files.
// Called by build-dict.sh after downloading.
//
// Usage: gen-dict.js <dict-dir> <"name1 name2 ..."> <"Src1:Rev1 Src2:Rev2 ...">
//   arg 1: directory containing .txt files
//   arg 2: space-separated list of dictionary names to generate
//   arg 3: space-separated list of "Source:Target" reverse map pairs

const fs = require("fs");

const dir = process.argv[2];
const names = (process.argv[3] || "").split(" ").filter(Boolean);
const reversePairs = (process.argv[4] || "")
  .split(" ")
  .filter(Boolean)
  .map((pair) => pair.split(":"));
// Dictionaries that must keep identity entries (key === value) as phrase shields.
const keepIdentitySet = new Set((process.argv[5] || "").split(" ").filter(Boolean));

if (!dir || names.length === 0) {
  console.error('Usage: gen-dict.js <dict-dir> <"name1 name2"> <"Src:Rev ..."> [<"keepIdentity1 ...">]');
  process.exit(1);
}

// Read a .txt dictionary file and return an array of [key, value] pairs.
//
// Each line looks like: "key\tvalue1 value2"
// We only take the first value. By default, lines where key === value are
// skipped (no conversion needed). Set keepIdentity = true to preserve them —
// identity entries act as "shields" that prevent shorter character-level rules
// from splitting a phrase (e.g. TWVariantsRevPhrases shields "口吃" from the
// character-level "吃→喫" in TWVariantsRev).
function parseDict(name, { keepIdentity = false } = {}) {
  const text = fs.readFileSync(dir + "/" + name + ".txt", "utf8");
  const lines = text.split("\n");
  const entries = [];

  for (const line of lines) {
    if (!line || line.startsWith("#")) {
      continue;
    }

    const parts = line.split("\t");
    const key = parts[0];
    const value = (parts[1] || "").split(" ")[0];

    if (key && value && (keepIdentity || key !== value)) {
      entries.push([key, value]);
    }
  }

  return entries;
}

// Write a TypeScript module file from [key, value] pairs.
function writeModule(name, entries) {
  const lines = [
    "// Auto-generated by scripts/build-dict.sh — do not edit",
    "// Source: https://github.com/BYVoid/OpenCC (Apache-2.0)",
    "const d: [string, string][] = [",
  ];

  for (const [k, v] of entries) {
    lines.push("  [" + JSON.stringify(k) + ", " + JSON.stringify(v) + "],");
  }

  lines.push("];", "export default d;", "");
  fs.writeFileSync(dir + "/" + name + ".ts", lines.join("\n"));
}

// Generate forward maps
for (const name of names) {
  let entries = parseDict(name, { keepIdentity: keepIdentitySet.has(name) });
  if (EXCLUSIONS[name]) {
    const before = entries.length;
    entries = entries.filter(([k]) => !EXCLUSIONS[name].has(k));
    if (entries.length < before) {
      console.log(`    ${name}: removed ${before - entries.length} excluded entries`);
    }
  }
  writeModule(name, entries);
}

// Generate reverse maps (swap key↔value)
for (const [src, rev] of reversePairs) {
  let entries = parseDict(src).map(([k, v]) => [v, k]);
  if (EXCLUSIONS[rev]) {
    const before = entries.length;
    entries = entries.filter(([k]) => !EXCLUSIONS[rev].has(k));
    if (entries.length < before) {
      console.log(`    ${rev}: removed ${before - entries.length} excluded entries`);
    }
  }
  writeModule(rev, entries);
}

// Augment TWVariantsRevPhrases with shields from STPhrases.
//
// TWVariantsRev maps single characters (e.g. 么→幺). When a simplified phrase
// like "什么" passes through tw2s/tw2sp, the character-level rule incorrectly
// converts it to "什幺". OpenCC's TWVariantsRevPhrases already shields some
// phrases (吃, 著, 凶, 口) but misses others (么). We scan STPhrases for any
// phrase whose simplified form contains a TWVariantsRev key and add identity
// shields so the phrase is matched whole and left intact.
{
  // TWVariantsRev is the reverse of TWVariants (value→key).
  const revKeys = new Set(parseDict("TWVariants").map(([, v]) => v));
  const existing = new Map(parseDict("TWVariantsRevPhrases", { keepIdentity: true }).map(([k, v]) => [k, v]));
  const stPhrases = parseDict("STPhrases");

  let added = 0;
  for (const [k] of stPhrases) {
    if (!existing.has(k) && [...revKeys].some((ch) => k.includes(ch))) {
      existing.set(k, k);
      added++;
    }
  }

  if (added > 0) {
    writeModule("TWVariantsRevPhrases", Array.from(existing.entries()));
    console.log(`    TWVariantsRevPhrases: +${added} phrase shields from STPhrases`);
  }
}
